### ISSUE TITLE
flow improvement

### ISSUE THREAD

**Issue by olivierb2** [Noviat/account_ebics#2]
Dear Noviat,

Thanks for this module which does the job for me. May I suggest some improvement in order to optimize the import flow. Please take in consideration my following limitation, not sure if this is applied to all bank.

- When I'm download a period, one file per day is downloaded.
- Some XML files does'nt contains banking data (normal when a day doesn't have move).

Here my process:

- Click on "EBICS Download" then choose a period (e.g last month).
- From the list of file downloaded, click on the first one.
- Click on "Process", if the file doesn't contain moves, click on "Action" and "Delete".

This process is working, but do you know if there is some way or you planned to make something like:

- Merge moves into a choosed period (e.g. having a bank statement for the month).
- Automatically delete or ignore XML that are not containing moves.

Thanks

Olivier.

**Comment by luc-demeyer** [comment]
Olivier,

- the banks for which I have configured the ebics module didn't sent empty files. Can you send me such an empty XML file so that I can have a look ? You can send that file offline to luc.demeyer@noviat.com.
- which odoo version are you running ?
- concerning process flow: can we schedule a short tel. call so that I have a clear picture of your requirements (you can send your contact details to my e-mail address).

**Comment by luc-demeyer** [comment]
Empty files can now be handled via the 'set to done' button (added to account_ebics 10.0 and 11.0).
For 11.0 version the code now also sets the status automatically to 'done' when an empty camt statement is received (for 10.0 the fix doesn't go so far, this action needs to be done manually.
