### ISSUE TITLE
Multiple Signature for file upload

### ISSUE THREAD

**Issue by TeoGoddet** [Noviat/account_ebics#31]
Hello ! 
Is this module capable to handle multiple signature on a payment file ? 

thanks !

**Comment by luc-demeyer** [comment]
This feature is not supported in the current version of this module and would require considerable development effort to do it in a clean way (javascript development to do client side signing since you don't want to store a user's private key on the odoo server.
Hence we recommend to use only the transport signature and sign with the banking app (hence use the certifcate of the mobile phone to sign). Many banks do have such a mobile banking app.
