### ISSUE TITLE
account_ebics migration to v14 status and migrations folder

### ISSUE THREAD

**Issue by BT-cjimeno** [Noviat/account_ebics#33]
Hi, I would like to know if the module account_ebics is migrated for version 14.

I ask this because I've tried installing it in v14 and got no errors, however I dont see any PR talking about migration to v14 and the default branch of this repository is 13.0.

I wanted to ask too about the migrations folder inside the v14 account_ebics module. I saw it has subfolders for 13.0.X, but I think those subfolders should not be there in 14.0 if I'm not wrong, I haven't played around with this feature ever, so I'm not really sure.

I saw the line "Remove any possible migration script from previous version." in this OCA guidelines:
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0
and that is what I understood.

Thanks.

**Comment by luc-demeyer** [comment]
@BT-cjimeno 
The module works ok for v14.
You may experience problems with the very latest patch level of the Odoo Enterprise camt parser. As a bypass you can use the OCA one until we have fixed this (or anyelse makes a PR to fix it).

Since this module is not published via the OCA we do not need to follow the guidelines and remove the 13.0.x migration scripts. This can be useful if you use the Odoo Enterprise migration service in stead of the OCA OpenUpgrade.
